//==============================//
//          2017 秋番清單
//  github.com/gnehs/Anime-List
//==============================//
//            資料來源
// 【秋番】2017年10月新番一覽（日本秋季新番列表）
// http://justlaughtw.blogspot.com/2017/03/201710.html
// 維基百科
// https://zh.wikipedia.org/
//==============================//
Anime = [
    // 星期格式 / Week
    //     Sun  Mon Tue  Wed  Thu  Fri  Sat none
    //     日   一   二   三    四   五   六  尚未公開
    // 原作載體 / Carrier
    //     Comic  Novel   Game  Original
    //    漫畫    小說    遊戲   原創或其他
    // 資料存取範例 / Example
    //    -> Anime[0].name
    //    <- LoveLive! SunShine!!
    {
        name: 'LoveLive! SunShine!!',
        date: '尚未公開',
        week: 'none',
        time: '尚未公開',
        carrier: 'Original',
        season: '2',
        nameInJpn: 'LoveLive! SunShine!!',
        img: 'http://i.imgur.com/FbMfs4G.png',
        description: "故事以日本靜岡縣的浦之星女學院為故事舞台，描述憧憬著 μ's 的主角之一高海千歌，將在這小地方與夥伴們朝著校園偶像的目標邁進。",
    },
    {
        name: '血界戰線',
        date: '尚未公開',
        week: 'none',
        time: '尚未公開',
        carrier: 'Comic',
        season: '2',
        nameInJpn: '血界戦線',
        img: 'https://i.imgur.com/qo03WHb.png',
        description: '紐約一晚便消失無蹤，取而代之的是異界與人界連接點「赫爾沙雷姆茲·羅特」，秘密結社萊布拉為了世界平衡和守護正常秩序而出動。',
    },
    {
        name: '鬼燈的冷徹',
        date: '尚未公開',
        week: 'none',
        time: '尚未公開',
        carrier: 'Comic',
        season: '2',
        nameInJpn: '鬼灯の冷徹',
        img: 'https://i.imgur.com/5mjlBsI.png',
        description: '故事描述戰後人口爆發且惡靈兇暴化，亡者產生的問題使的地獄出現了前所未有混亂；身為閻羅王手下的第一補佐官鬼燈，將替代閻羅王將解決各式麻煩的問題，地獄也每天都上演著閻羅王翹班挨罵的情景。',
    },
    {
        name: '3 月的獅子',
        date: '尚未公開',
        week: 'none',
        time: '尚未公開',
        carrier: 'Comic',
        season: '2',
        nameInJpn: '3月のライオン',
        img: 'https://i.imgur.com/QID5pXV.png',
        description: '描述獨自居住在東京舊市鎮的 17 歲少年 桐山零，被周遭歌頌為天才將棋棋士的零，在幼時因意外事故失去了家人，所以生活上、還是棋盤上都背負著深沉的孤獨。在這樣的他面前卻出現了明里、日向、桃三姊妹......',
    },
    {
        name: '結城友奈是勇者',
        date: '尚未公開',
        week: 'none',
        time: '尚未公開',
        carrier: 'Original',
        season: '2',
        nameInJpn: '結城友奈は勇者である',
        img: 'https://i.imgur.com/YTYZSEt.png',
        description: '描述結城友奈是位國中二年級的學生，每天從家裡到學校上課的她也結交了不少的朋友，過著隨處可見的平穩的日子，但唯一跟一般人不同之處就是她所參與的社團勇者部。以社長犬吠埼風為中心，結城友奈所屬的勇者部即將開始活動。',
    },
    {
        name: '我家有個魚乾妹',
        date: '尚未公開',
        week: 'none',
        time: '尚未公開',
        carrier: 'Comic',
        season: '2',
        nameInJpn: '干物妹! うまるちゃん',
        img: 'https://i.imgur.com/cLFUhKD.png',
        description: '故事背景設定在東京都八王子市，講述的是一位在外面是嫻熟高貴、但回到家後立即變成宅在家中喜歡 ACG 的乾物女小埋，與照顧她生活的哥哥以及好友們之間發生的喜劇故事。',
    },
    {
        name: '阿松',
        date: '尚未公開',
        week: 'none',
        time: '尚未公開',
        carrier: 'Comic',
        season: '2',
        nameInJpn: 'おそ松くん',
        img: 'https://i.imgur.com/vaKu2s0.png',
        description: '故事以過去的經典作品《六胞胎》中，登場的 6 位主角設定為 20 多歳的成年人，內容多為原創。故事圍繞著松野家的六胞胎進行，描述他們的日常生活種種。',
    },
    {
        name: 'Classica Loid',
        date: '尚未公開',
        week: 'none',
        time: '尚未公開',
        carrier: 'Original',
        season: '2',
        nameInJpn: 'クラシカロイド',
        img: 'https://i.imgur.com/LkKqPQ8.png',
        description: '描述住在依靠音樂來振興都市中的高中生面前，突然出現了由貝多芬和莫扎特兩人所組成的可疑音樂組合。他們所演奏的音樂中有著奇妙的力量，可以引發星辰降落、巨大機器人出現等怪事，讓他們每天過得提心吊膽……',
    },
    {
        name: 'LOVE 米 -WE LOVE RICE-',
        date: '尚未公開',
        week: 'none',
        time: '尚未公開',
        carrier: 'Original',
        season: '2',
        nameInJpn: 'ラブ米 -WE LOVE RICE-',
        img: 'https://i.imgur.com/Mm1ppLb.png',
        description: '描述是一部將日本主食米飯擬人化的作品。剛進入即將面臨廢校的穀立稻穗學園就讀的五位新生，為了從麵包手中奪回穀物的人氣，組成了名為「LOVE RICE」的團體，朝向宣傳穀物美味的舞台邁進。',
        //不懂為啥可以賣米到第二季...
    },
    {
        name: 'Wake Up,Girls！',
        date: '尚未公開',
        week: 'none',
        time: '尚未公開',
        carrier: 'Original',
        season: '2',
        nameInJpn: 'Wake Up, Girls！',
        img: 'https://i.imgur.com/gKqOsHY.png',
        description: '描述在日本東北的仙台有個即倒閉的弱小事務所，雖然過去有魔術師、寫真偶像、占卜師等的藝人，但目前旗下就連一名藝人也沒有。為了解除這個危機，事務所的社長 丹下決定推出一個偶像團體……',
    },
    {
        name: '偶像夢幻祭',
        date: '尚未公開',
        week: 'none',
        time: '尚未公開',
        carrier: 'Game',
        season: '2',
        nameInJpn: 'あんさんぶるスターズ！',
        img: 'https://i.imgur.com/4K06FRV.png',
        description: '描述某天突然被傳說中的偶像三神遙人選中的高中 2 年級主人公·天宮奏。 他看到同事務所的偶像們那熱切的心意，也不甘落後地沉浸在偶像活動當中。 於是，他和夥伴們一同以在夢之祭中出場，並贏得 CD 出道為目標！ ',
    },
    {
        name: '123',
        date: '尚未公開',
        week: 'none',
        time: '尚未公開',
        carrier: '123',
        season: '1232',
        nameInJpn: '123',
        img: '123',
        description: '123',
    },
    {
        name: '123',
        date: '尚未公開',
        week: 'none',
        time: '尚未公開',
        carrier: '123',
        season: '1232',
        nameInJpn: '123',
        img: '123',
        description: '123',
    },
    {
        name: '123',
        date: '尚未公開',
        week: 'none',
        time: '尚未公開',
        carrier: '123',
        season: '1232',
        nameInJpn: '123',
        img: '123',
        description: '123',
    },
    {
        name: '123',
        date: '尚未公開',
        week: 'none',
        time: '尚未公開',
        carrier: '123',
        season: '1232',
        nameInJpn: '123',
        img: '123',
        description: '123',
    },
    {
        name: '123',
        date: '尚未公開',
        week: 'none',
        time: '尚未公開',
        carrier: '123',
        season: '1232',
        nameInJpn: '123',
        img: '123',
        description: '123',
    },
    {
        name: '123',
        date: '尚未公開',
        week: 'none',
        time: '尚未公開',
        carrier: '123',
        season: '1232',
        nameInJpn: '123',
        img: '123',
        description: '123',
    },
    /*{
        name: '123',
        date: '尚未公開',
        week: 'none',
        time: '尚未公開',
        carrier: '123',
        season: '1232',
        nameInJpn: '123',
        img: '123',
        description: '123',
    },*/

]