//==============================//
//          2017 秋番清單
//  github.com/gnehs/Anime-List
//==============================//
//            資料來源
// 【秋番】2017年10月新番一覽（日本秋季新番列表）
// http://justlaughtw.blogspot.com/2017/03/201710.html
// 維基百科
// https://zh.wikipedia.org/
// 萌娘百科
// https://zh.moegirl.org/
//==============================//
Anime = [
    // 星期格式 / Week
    //     Sun  Mon Tue  Wed  Thu  Fri  Sat none
    //     日   一   二   三    四   五   六  尚未公開
    // 原作載體 / Carrier
    //     Comic  Novel   Game  Original
    //    漫畫    小說    遊戲   原創或其他
    // 資料存取範例 / Example
    //    -> Anime[0].name
    //    <- LoveLive! SunShine!!
    {
        name: 'LoveLive! SunShine!!',
        date: '尚未公開',
        week: 'none',
        time: '尚未公開',
        carrier: 'Original',
        season: '2',
        nameInJpn: 'LoveLive! SunShine!!',
        img: 'http://i.imgur.com/FbMfs4G.png',
        description: "故事以日本靜岡縣的浦之星女學院為故事舞台，描述憧憬著 μ's 的主角之一高海千歌，將在這小地方與夥伴們朝著校園偶像的目標邁進。",
    },
    {
        name: '血界戰線',
        date: '尚未公開',
        week: 'none',
        time: '尚未公開',
        carrier: 'Comic',
        season: '2',
        nameInJpn: '血界戦線',
        img: 'https://i.imgur.com/qo03WHb.png',
        description: '紐約一晚便消失無蹤，取而代之的是異界與人界連接點「赫爾沙雷姆茲·羅特」，秘密結社萊布拉為了世界平衡和守護正常秩序而出動。',
    },
    {
        name: '鬼燈的冷徹',
        date: '尚未公開',
        week: 'none',
        time: '尚未公開',
        carrier: 'Comic',
        season: '2',
        nameInJpn: '鬼灯の冷徹',
        img: 'https://i.imgur.com/5mjlBsI.png',
        description: '故事描述戰後人口爆發且惡靈兇暴化，亡者產生的問題使的地獄出現了前所未有混亂；身為閻羅王手下的第一補佐官鬼燈，將替代閻羅王將解決各式麻煩的問題，地獄也每天都上演著閻羅王翹班挨罵的情景。',
    },
    {
        name: '3 月的獅子',
        date: '尚未公開',
        week: 'none',
        time: '尚未公開',
        carrier: 'Comic',
        season: '2',
        nameInJpn: '3月のライオン',
        img: 'https://i.imgur.com/QID5pXV.png',
        description: '描述獨自居住在東京舊市鎮的 17 歲少年 桐山零，被周遭歌頌為天才將棋棋士的零，在幼時因意外事故失去了家人，所以生活上、還是棋盤上都背負著深沉的孤獨。在這樣的他面前卻出現了明里、日向、桃三姊妹......',
    },
    {
        name: '結城友奈是勇者',
        date: '尚未公開',
        week: 'none',
        time: '尚未公開',
        carrier: 'Original',
        season: '2',
        nameInJpn: '結城友奈は勇者である',
        img: 'https://i.imgur.com/YTYZSEt.png',
        description: '描述結城友奈是位國中二年級的學生，每天從家裡到學校上課的她也結交了不少的朋友，過著隨處可見的平穩的日子，但唯一跟一般人不同之處就是她所參與的社團勇者部。以社長犬吠埼風為中心，結城友奈所屬的勇者部即將開始活動。',
    },
    {
        name: '我家有個魚乾妹',
        date: '尚未公開',
        week: 'none',
        time: '尚未公開',
        carrier: 'Comic',
        season: '2',
        nameInJpn: '干物妹! うまるちゃん',
        img: 'https://i.imgur.com/cLFUhKD.png',
        description: '故事背景設定在東京都八王子市，講述的是一位在外面是嫻熟高貴、但回到家後立即變成宅在家中喜歡 ACG 的乾物女小埋，與照顧她生活的哥哥以及好友們之間發生的喜劇故事。',
    },
    {
        name: '阿松',
        date: '尚未公開',
        week: 'none',
        time: '尚未公開',
        carrier: 'Comic',
        season: '2',
        nameInJpn: 'おそ松くん',
        img: 'https://i.imgur.com/vaKu2s0.png',
        description: '故事以過去的經典作品《六胞胎》中，登場的 6 位主角設定為 20 多歳的成年人，內容多為原創。故事圍繞著松野家的六胞胎進行，描述他們的日常生活種種。',
    },
    {
        name: 'Classica Loid',
        date: '尚未公開',
        week: 'none',
        time: '尚未公開',
        carrier: 'Original',
        season: '2',
        nameInJpn: 'クラシカロイド',
        img: 'https://i.imgur.com/LkKqPQ8.png',
        description: '描述住在依靠音樂來振興都市中的高中生面前，突然出現了由貝多芬和莫扎特兩人所組成的可疑音樂組合。他們所演奏的音樂中有著奇妙的力量，可以引發星辰降落、巨大機器人出現等怪事，讓他們每天過得提心吊膽……',
    },
    {
        name: 'LOVE 米 -WE LOVE RICE-',
        date: '尚未公開',
        week: 'none',
        time: '尚未公開',
        carrier: 'Original',
        season: '2',
        nameInJpn: 'ラブ米 -WE LOVE RICE-',
        img: 'https://i.imgur.com/Mm1ppLb.png',
        description: '描述是一部將日本主食米飯擬人化的作品。剛進入即將面臨廢校的穀立稻穗學園就讀的五位新生，為了從麵包手中奪回穀物的人氣，組成了名為「LOVE RICE」的團體，朝向宣傳穀物美味的舞台邁進。',
        //不懂為啥可以賣米到第二季...
    },
    {
        name: 'Wake Up,Girls！',
        date: '尚未公開',
        week: 'none',
        time: '尚未公開',
        carrier: 'Original',
        season: '2',
        nameInJpn: 'Wake Up, Girls！',
        img: 'https://i.imgur.com/gKqOsHY.png',
        description: '描述在日本東北的仙台有個即倒閉的弱小事務所，雖然過去有魔術師、寫真偶像、占卜師等的藝人，但目前旗下就連一名藝人也沒有。為了解除這個危機，事務所的社長 丹下決定推出一個偶像團體……',
    },
    {
        name: '偶像夢幻祭',
        date: '尚未公開',
        week: 'none',
        time: '尚未公開',
        carrier: 'Game',
        season: '2',
        nameInJpn: 'あんさんぶるスターズ！',
        img: 'https://i.imgur.com/4K06FRV.png',
        description: '描述某天突然被傳說中的偶像三神遙人選中的高中 2 年級主人公·天宮奏。 他看到同事務所的偶像們那熱切的心意，也不甘落後地沉浸在偶像活動當中。 於是，他和夥伴們一同以在夢之祭中出場，並贏得 CD 出道為目標！ ',
    },
    {
        name: '灰姑娘女孩劇場',
        date: '尚未公開',
        week: 'none',
        time: '尚未公開',
        carrier: 'Comic',
        season: '2',
        nameInJpn: 'アイドルマスターシンデレラガールズ劇場',
        img: 'https://i.imgur.com/FOButed.jpg',
        description: '正好評配信中的偶像培養遊戲《偶像大師 灰姑娘女孩》，在該遊戲內展開的《灰姑娘女孩劇場》，作為TV動畫嶄新登場！熟悉的偶像們，今天也是非常地吵鬧！？包含平常未被描寫的偶像們度過假期的方式，和偶像們的滑稽劇等豐富多彩內容的情緒高漲的短篇動畫，終於要開幕了♪',
    },
    {
        name: '食戟之靈',
        date: '尚未公開',
        week: 'none',
        time: '尚未公開',
        carrier: 'Comic',
        season: '3',
        nameInJpn: '食戟のソーマ',
        img: 'https://i.imgur.com/ErcOiq6.png',
        description: '作品的舞台是位於東京內的一所料理名校「遠月學園」，國中畢業之後為了作繼承家業「幸平餐館」的主角幸平創真因為父親的指示來到這裡，以特別編入生就讀。在畢業率不到百分之十的「遠月學園」裏，來自各地廚藝精銳的年輕人彼此較勁，是互相爭奪料理頂點的戰場。在這料理便是一切的世界，所有敵人都必須用料理來征服。為了擊敗對手，互相賭上等價的賭注，用料理進行的單對單決鬥，就是遠月的傳統料理對決－「食戟」。',
    },
    {
        name: '銀魂',
        date: '尚未公開',
        week: 'none',
        time: '尚未公開',
        carrier: 'Comic',
        season: '6',
        nameInJpn: 'ぎんたま',
        img: 'https://i.imgur.com/r50dGl8.png',
        description: '故事描述在江戶，因為突然從宇宙來的異人「天人」勢力的抬頭加上頒布廢刀令，使得武士走上衰退的道路。但是有個人依然堅持武士的靈魂名為坂田銀時。這個喜歡吃甜食又無厘頭的傢伙，說不定能將腐敗的江戶給一分為二呢。',
    },
    {
        name: '悠久持有者',
        date: '尚未公開',
        week: 'none',
        time: '尚未公開',
        carrier: 'Comic',
        season: '1',
        nameInJpn: 'UQ Holder!',
        img: 'https://i.imgur.com/Ty7GhlZ.png',
        description: '2086年，世人皆知魔法之存在已經10年。近衛刀太住在日本熊本縣阿蘇郡（見第45話），夢想去首都「新東京天之御柱市」做一番大事業，但被村長要求：先打倒他的班導師兼監護人雪姬，才能啟程前往天之御柱市。刀太與同班四位男同學是好朋友，他們每天挑戰雪姬，希望能打倒她，但總是無功而返；雪姬覺得他們自不量力，卻也樂在其中。賞金獵人橘老師突襲雪姬，終結了這段平穩的日子。',
    },
    {
        name: '魔法使的新娘',
        date: '尚未公開',
        week: 'none',
        time: '尚未公開',
        carrier: 'Comic',
        season: '1',
        nameInJpn: '魔法使いの嫁',
        img: 'https://i.imgur.com/NeOAq5H.png',
        description: '羽鳥智世是個無依無靠，沒有求生慾望和方法，一無所有的十五歲少女，卻有一名非人類的魔法使艾利亞斯·恩滋華斯以五百萬磅買下智世，並把她當成「徒弟」和「新娘」，她心中停止已久的時間也開始慢慢地運轉……',
    },
    {
        name: '泥鯨之子們在沙地上歌唱',
        date: '尚未公開',
        week: 'none',
        time: '尚未公開',
        carrier: 'Comic',
        season: '1',
        nameInJpn: 'クジラの子らは砂上に歌う',
        img: 'https://i.imgur.com/E5zslbk.png',
        description: '以一個被沙子覆蓋的世界作為舞台，居住在砂海上的巨大船「泥鯨」的居民們，是擁有著以感情為發動來源的超能力「情念動」的短命種族。背負著此般命運的少年茶珂珞，某天在突然漂流而來的廢墟船中，與一名少女相遇了……',
    },
    {
        name: '123',
        date: '尚未公開',
        week: 'none',
        time: '尚未公開',
        carrier: '123',
        season: '1232',
        nameInJpn: '123',
        img: '123',
        description: '123',
    },
    {
        name: '123',
        date: '尚未公開',
        week: 'none',
        time: '尚未公開',
        carrier: '123',
        season: '1232',
        nameInJpn: '123',
        img: '123',
        description: '123',
    },
    {
        name: '123',
        date: '尚未公開',
        week: 'none',
        time: '尚未公開',
        carrier: '123',
        season: '1232',
        nameInJpn: '123',
        img: '123',
        description: '123',
    },
    {
        name: '123',
        date: '尚未公開',
        week: 'none',
        time: '尚未公開',
        carrier: '123',
        season: '1232',
        nameInJpn: '123',
        img: '123',
        description: '123',
    },
    {
        name: '123',
        date: '尚未公開',
        week: 'none',
        time: '尚未公開',
        carrier: '123',
        season: '1232',
        nameInJpn: '123',
        img: '123',
        description: '123',
    },
    {
        name: '123',
        date: '尚未公開',
        week: 'none',
        time: '尚未公開',
        carrier: '123',
        season: '1232',
        nameInJpn: '123',
        img: '123',
        description: '123',
    },
    {
        name: '123',
        date: '尚未公開',
        week: 'none',
        time: '尚未公開',
        carrier: '123',
        season: '1232',
        nameInJpn: '123',
        img: '123',
        description: '123',
    },
    /*{
        name: '123',
        date: '尚未公開',
        week: 'none',
        time: '尚未公開',
        carrier: '123',
        season: '1232',
        nameInJpn: '123',
        img: '123',
        description: '123',
    },*/

]