//==============================//
//  2018 春番                    //
//  github.com/gnehs/Anime-List //
//==============================//
Anime = [{
        name: '鬼太郎',
        nameInJpn: 'ゲゲゲの鬼太郎',
        date: '4/1',
        time: '9:00',
        carrier: 'Comic',
        season: '6',
        episode: '',
        img: 'https://i.imgur.com/FlSmbcw.jpg',
        official: 'http://www.toei-anim.co.jp/kitaro/',
        description: '故事主軸是闡述作為幽靈族最後倖存者的少年「鬼太郎」，施展妖術和做盡壞事的妖怪們作戰。身穿黃黑橫紋背心和傳統日式木屐的小男孩，以頭髮、坎肩和下馱當武器，與一群住在神秘森林裡的妖怪朋友們一起解決妖怪跟人類兩個世界的麻煩。',
    },
    {
        name: 'B：彼之初',
        nameInJpn: 'B: The Beginning',
        date: '3/2',
        time: '0:00',
        carrier: 'Original',
        season: '1',
        episode: '12',
        img: 'https://i.imgur.com/iGT3yO2.jpg',
        official: 'http://www.b-animation.jp/',
        description: '某天，被稱為天才調查員的奇斯·弗列克來到王立警察特殊犯罪搜査科，並追尋著某件事件的犯人——連環殺手「殺手B」。而在犯案現場內，連環殺手「殺手B」必會刻上字母「B」，總是引起人們的注意，但沒有人知道其意思。「B」只是殺手留給她的信息，想告訴她「我在這裡」。奇斯及黑羽，這兩位陌生人的命運，不久將被一個陰謀吞噬。',
    },
    {
        name: '裝刀凱',
        nameInJpn: 'ソードガイ The Animation',
        date: '3/23',
        time: '0:00',
        carrier: 'Comic',
        season: '1',
        episode: '12',
        img: 'https://i.imgur.com/jHxwmvQ.png',
        official: 'http://swordgai-anime.com/',
        description: '嘗遍無數人鮮血的武器化為傳奇，有時甚至全然不受人控制。當與武器合而為一的人類宿主心中充滿憎恨與殺意時，就會如同惡魔一般渴望大開殺戒。某組織面對這類危險武器的存在長達好幾世紀，而一位名叫「凱」的男子則注定與武器合而為一…',
    },

    {
        name: '甜蜜懲罰～我是看守專用寵物',
        nameInJpn: '甘い懲罰～私は看守専用ペット',
        date: '4/1',
        time: '01:00',
        carrier: 'Comic',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/Wd15gut.jpg',
        official: 'https://kanshu.cf-anime.com',
        description: '早乙女陽菜因為冤罪進入了監獄當中，而負責她的是一位大帥哥看守明神亞貴，而陽菜成為了這個看守的專屬玩具，在牢裡除了這個抖 S 看守外還有為了保護女主角而奔走的黑社會比嘉大和，陽菜本身在監獄外面還有一位男朋友八雲聖德',
    },
    {
        name: '冷然之天秤',
        nameInJpn: 'ニル・アドミラリの天秤',
        date: '4/1',
        time: '22:00',
        carrier: 'Game',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/CWVUs95.jpg',
        official: 'http://nilad-anime.com/',
        description: '故事背景在大正25年間。大地震之後，帝都東京以「和洋混合」的獨特文化形式繼續發展，隨著科技現代化、印刷出版日漸興盛，接連發生了一系列無法解開的謎事件。',
    },
    {
        name: '賽馬娘Pretty Derby',
        nameInJpn: 'ウマ娘 プリティーダービー',
        date: '4/1',
        time: '24:00',
        carrier: 'Game',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/2DAb1dy.png',
        official: 'http://anime-umamusume.jp/',
        description: '這是從異世界傳承下光輝的名字與競跑能力的“馬娘”，自古以來與人類共存著的世界的故事。從鄉下轉學到大都市的訓中學園的馬娘·特別週，與同學們互相切磋、賭上“日本第一馬娘”的稱號，目標：在“Twinkle系列賽”中的勝利！',
    },
    {
        name: '足球小將翼',
        nameInJpn: 'キャプテン翼',
        date: '4/2',
        time: '01:35',
        carrier: 'Comic',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/5PaQixS.png',
        official: 'http://ball-ha-tomodachi.com/',
        description: '內容講述足球技術高超的少年大空翼從小學六年級開始到進入職業足壇之間所發生的故事。',
    },
    {
        name: '龍族拼圖',
        nameInJpn: 'パズドラ',
        date: '4/2',
        time: '18:25',
        carrier: 'Game',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/vozo1qg.jpg',
        official: 'http://www.tv-tokyo.co.jp/anime/pad/',
        description: '以《龍族拼圖X》改編，描述主人公和怪物夥伴們展開的熱血友情成長的冒險故事。',
    },
    {
        name: '你還不懂群馬',
        nameInJpn: 'お前はまだグンマを知らない',
        date: '4/2',
        time: '20:55',
        carrier: 'Comic',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/Jz57X2B.jpg',
        official: 'https://omagun.com/',
        description: '本作敘述男高中生神月紀從千葉縣轉學來群馬縣，沒想到在新幹線上發生了令人匪夷所思的事情。朋友奉勸他不要來，這裡沒人能活著出去。這輛列車在到達群馬縣之前，不會在任何車站開門。車上乘客都是一看就是不正常的人，他還要在被捆綁的情況下回答奇葩的問題......。',
    },
    {
        name: '魔法少女 我',
        nameInJpn: '魔法少女 俺',
        date: '4/2',
        time: '22:00',
        carrier: 'Comic',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/QbD5eZn.jpg',
        official: 'http://magicalgirl-ore.com/',
        description: '主角卯野咲是新生偶像團體「Magical Twin」的成員，為了守護自己所憧憬的偶像團體「STAR☆RICE」成員御翔桃拾而願意奉獻一切。就在某一天，她得知母親曾經是魔法少女而感到震驚。然後，咲為了守護桃拾的願望而變成了男性形態的「魔法少女」。',
    },
    {
        name: '妖怪旅館營業中',
        nameInJpn: 'かくりよの宿飯',
        date: '4/2',
        time: '22:30',
        carrier: 'Novel',
        season: '1',
        episode: '26',
        img: 'https://i.imgur.com/uvMoQkr.jpg',
        official: 'http://kakuriyo-anime.com/',
        description: '老字號旅館「天神屋」，座落於妖魔鬼怪所棲息的世界──隱世。看得見妖怪的善良女大學生葵，不知不覺中養成做料理餵食妖怪的習慣。某天，葵在餵食妖怪時，突然被天神屋的「大老闆」鬼神給抓走了。根據大老闆所言，葵成了祖父欠下巨債的「擔保品」，必須嫁入他們家。',
    },
    {
        name: '宇宙戰艦提拉米斯',
        nameInJpn: '宇宙戦艦ティラミス',
        date: '4/3',
        time: '0:00',
        carrier: 'Comic',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/LD7atZF.jpg',
        official: 'http://tiramisu-anime.com/',
        description: '主角是前途似錦的王牌駕駛員一之瀨昴，但不善交際的他在船上一直交不到朋友，也因此總是莫名其妙地做出一些搞笑的脫序行為…… ',
    },
    {
        name: '鋼彈創鬥者潛網大戰',
        nameInJpn: 'ガンダムビルドダイバーズ',
        date: '4/2',
        time: '25:00',
        carrier: 'Comic',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/Jv269fe.jpg',
        official: 'http://tiramisu-anime.com/',
        description: '主角是前途似錦的王牌駕駛員一之瀨昴，但不善交際的他在船上一直交不到朋友，也因此總是莫名其妙地做出一些搞笑的脫序行為…… ',
    },
    {
        name: '東京喰種：re',
        nameInJpn: '東京喰種：re',
        date: '4/3',
        time: '23:00',
        carrier: 'Comic',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/xROkprA.jpg',
        official: 'http://www.marv.jp/special/tokyoghoul/',
        description: '混在人群當中，吞食人類的血肉。儘管擁有人類的外觀，卻是與人類相異的存在…”喰種”。負責驅逐、研究”喰種”的〔CCG〕，為了完成某個命題，新設立一個實驗體集團。──其名稱是「Qs昆克斯」。非「一般人類」的他們，與佐佐木琲世一等搜查官，他們在”東京”這座城市要面對的東西會是什麼──？',
    },
    {
        name: '立花館戀愛三角關係',
        nameInJpn: '立花館To Lieあんぐる',
        date: '4/3',
        time: '25:00',
        carrier: 'Comic',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/LovtWHF.jpg',
        official: 'http://tachibanakan-anime.com/',
        description: '夏乃花火回到她在六年前離開的鄉下城鎮就讀高中，原本應該入住時尚宿舍「橘館」的她卻因為阿姨的疏失，來到破舊公寓「立花館」開始新生活。夏乃花火在那裡遇見她的兒時玩伴與幾位奇怪的房客，並決定要在完成住滿一個月的租約後搬離立花館。',
    },
    {
        name: '魯邦三世 PART5',
        nameInJpn: 'ルパン三世 PART5',
        date: '4/3',
        time: '25:29',
        carrier: 'Comic',
        season: '5',
        episode: '',
        img: 'https://i.imgur.com/syTVZCK.jpg',
        official: 'https://lupin-pt5.com/',
        description: '魯邦三世是怪盜紳士亞森·魯邦的孫子，被稱為世界最傑出的神偷，在偷東西前總是會發出預告信。他與拔槍只需0.3秒的神槍手次元大介，神秘歐亞混血女盜峰不二子，無所不斬的居合道高手石川五右衛門合作偷遍全世界。錢形平次的後裔，警部錢形幸一一直想要逮捕他們，但全部以失敗告終。',
    },
    {
        name: '3D彼女',
        nameInJpn: '3D彼女 リアルガール',
        date: '4/3',
        time: '25:59',
        carrier: 'Comic',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/Zz73HM8.jpg',
        official: 'http://www.3dkanojo-anime.com/',
        description: '筒井光，是一個滿足於動漫以及遊戲中虛擬女孩的高中生。某一天，陷入和現充女色葉一起被罰清掃游泳池的窘境。打扮花哨又擺架子而且出了名和男生關係亂的百分百現充女‧色葉 謎樣地急速接近！不不不…你和我、完全就不是一路人啊！',
    },
    {
        name: 'ALICE OR ALICE 妹控哥哥與雙胞胎妹妹',
        nameInJpn: 'ありすorありす ～シスコン兄さんと双子の妹～',
        date: '4/4',
        time: '22:55',
        carrier: 'Comic',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/AF5bO4Q.jpg',
        official: 'http://alice-or-alice.com/',
        description: '這是一個由愛莉、莉絲兩個雙胞胎以及一個妹控哥哥組成的故事，寵溺妹妹的哥哥關於妹妹的事情無所不知！一面獨占著又寵溺著愛吃甜食、愛撒嬌妹妹們的萌萌日常生活。',
    },
    {
        name: '重神機潘多拉',
        nameInJpn: '重神機パンドーラ',
        date: '4/4',
        time: '23:30',
        carrier: 'Original',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/HY9APJH.jpg',
        official: 'http://www.project-the-next.com/',
        description: '描述環境因某起事故而發生劇變，由此誕生的超級生物給人們帶來了災難，被放逐的天才科學家主人公為了對抗這類生物而開展獨自研究。作品的舞台則是以中國重慶為原型。',
    },
    {
        name: '罪人與龍共舞',
        nameInJpn: 'されど罪人は竜と踊る',
        date: '4/5',
        time: '01:58',
        carrier: 'Novel',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/sx6I47Z.png',
        official: 'http://www.tbs.co.jp/anime/sareryu/',
        description: '所謂的咒式，乃操作作用子定數h，讓物理法則發生局部變化，產生TNT炸藥與毒氣，並引發電漿與核融合之類強烈物理現象的方程式。兩名使用咒式的進攻型咒式士，想擺脫惡運纏身的嘉優斯，以及殘酷的俊美劍士吉吉那。追尋「異貌者」和賞金通緝要犯的兩人，被捲入艾理達那上「龍」的戰爭以及大國的陰謀中……。',
    },
    {
        name: 'Aikatsu! 偶像學園！Friends',
        nameInJpn: 'アイカツフレンズ！',
        date: '4/5',
        time: '18:25',
        carrier: 'Game',
        season: '3',
        episode: '',
        img: 'https://i.imgur.com/J1KfnPj.jpg',
        official: 'http://www.aikatsu.com/friends/teaser/',
        description: '自 2012 年起推出的跨媒體企劃《Aikatsu! 偶像學園！》，橫跨卡牌遊戲、電視動畫、玩具以及服裝等產品，本次推出的《Aikatsu! 偶像學園！Friends》第三作，以「和朋友一起 Aikatsu! 」作為主題，是系列作中首度推出雙人組合，描繪兩人朝向頂尖偶像之路邁進的故事。ｚ',
    },
    {
        name: '多田君不談戀愛',
        nameInJpn: '多田くんは恋をしない',
        date: '4/5',
        time: '21:00',
        carrier: 'Original',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/LcdnnBF.jpg',
        official: 'http://tadakoi.tv/',
        description: '手持相機，拍攝盛開櫻花照片的多田光良，與剛剛從異國他鄉來到日本的少女特蕾莎·華格納相遇了。從歐洲的拉森堡來到日本留學的特蕾莎，剛一到達日本，就和一起過來的夥伴走散而迷路了。由此而開始幫助她的光良，將特蕾莎帶到了祖父經營的多田咖啡店……',
    },
    {
        name: '銀河英雄傳說 Die Neue These',
        nameInJpn: '銀河英雄伝説 Die Neue These 邂逅',
        date: '4/5',
        time: '22:30',
        carrier: 'Novel',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/kauJPuU.jpg',
        official: 'http://gineiden-anime.com/',
        description: '背景設定為人類生存圈擴展到全銀河系的未來時空。由於財富帶來糜爛，人們對政治失去信心，漸漸疏於履行民主之義務，野心家趁機奪權，重回專制體制，建立「銀河帝國」。不滿帝制的人民展開逃亡，成立自由行星同盟。從此兩國互相爭戰達150多年，加上夾在中間之強大經濟體——獨立城邦國家費沙自治領，以及背後的黑暗宗教勢力——地球教。宇宙曆796年（帝國曆487年）1月，亞斯提會戰爆發，萊因哈特·馮·羅嚴克拉姆和楊威利首次交鋒，銀河的歷史又翻過了一頁……。',
    },
    {
        name: '漫畫女孩',
        nameInJpn: 'こみっくがーるず',
        date: '4/5',
        time: '23:30',
        carrier: 'Comic',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/6CHzyzu.jpg',
        official: 'http://comic-girls.com/',
        description: '萌田薫子（筆名 薰子），15歳。職業為高中生、同時也是四格漫畫家！搬進漫畫家專用的女子宿舍的她， 在室友的少女漫畫家的小夢、TL漫畫家的琉姬以及少年漫畫家的翼等同伴們的圍繞下，今天也愉快地拿起筆繪製著分鏡、為了完稿正熬夜工作中！可愛又有趣、漫畫家的四格漫畫物語在此揭幕！',
    },
    {
        name: 'MEGALO BOX',
        nameInJpn: 'メガロボクス',
        date: '4/5',
        time: '25:28',
        carrier: 'Comic',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/cqaBgvp.jpg',
        official: 'http://megalobox.com/',
        description: '今天也立於未認可地區的賭博比賽賽場上的MEGALO拳擊手「Junk Dog」。雖然具備實力，卻只有靠比賽造假賺錢這一條生存之道，他為自己的「現在」感到心焦。但，他與孤高的冠軍·勇利相遇，作為MEGALO拳擊手，作為男人，向自己的「現在」發起挑戰——。',
    },
    {
        name: '閃電十一人 戰神的天秤',
        nameInJpn: 'イナズマイレブン アレスの天秤',
        date: '4/6',
        time: '17:55',
        carrier: 'Game',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/Xei5QNQ.jpg',
        official: 'http://www.tv-tokyo.co.jp/anime/inazuma2018/',
        description: '時間線坐落在第一部作品後的平行世界。雷門中學足球隊在Football Frontier大賽中取得優勝，閃電日本隊於Football Frontier International世界大賽慘敗，雷門Football Frontier大賽的奪冠成員全員以強化委員之名義，被分散到各地的國中，強化總體實力，此平行世界的中學足球隊必須有贊助商才能營運足球隊。之後，在伊那國島有一群熱愛足球的中學生，因為伊那國中學的校長覺得伊那國島無法繼續追隨足球的熱潮加上毫無經費請贊助商，從而廢止足球部。',
    },
    {
        name: '極道超女',
        nameInJpn: 'ヒナまつり',
        date: '4/6',
        time: '20:00',
        carrier: 'Comic',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/9drvwLM.png',
        official: 'http://hina-matsuri.net/',
        description: '支稱著蘆川組的年輕智力型黑道新田義史，過著被喜歡的壺所包圍的悠然自得單身生活。但某一天，隨著裝在神秘物體裡的少女雛來到他家，他的生活為之一變。他被能使用念動力的雛所脅迫，迫不得已開始和她同居！',
    },
    {
        name: '錢進球場',
        nameInJpn: 'グラゼニ',
        date: '4/6',
        time: '22:30',
        carrier: 'Comic',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/M2u9DOH.jpg',
        official: 'https://www.bs-sptv.com/gurazeni/',
        description: '凡田夏之介是一名高中畢業就加入職棒，年薪1800萬的選手，靠著左側投這項獨特的武器，他即使混得不上不下，仍有口飯吃。而在他眼中，職棒選手都是可以用錢去衡量的！年薪就代表著職棒選手的地位，即使當季表現再良好的選手，只要年薪不如自己，仍會被凡田瞧不起。透過這平凡的職棒選手，職棒不為人知的另外一面即將被揭露！',
    },
    {
        name: 'LOST SONG',
        nameInJpn: 'LOST SONG',
        date: '4/7',
        time: '0:00',
        carrier: 'Original',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/OHr054F.jpg',
        official: 'http://lost-song.com/',
        description: '住在邊境的村莊很有朝氣又有點貪吃的少女リン，深居奢華皇宮過著孤獨日子的歌姬フィーニス，二人都有著不同於一般人的力量『歌聲』，治癒傷、生出水、喚起風，那是一股能產生奇跡的力量',
    },
    {
        name: 'Lostorage conflated WIXOSS',
        nameInJpn: 'ロストレージインサイテッドウィクロス',
        date: '4/6',
        time: '24:30',
        carrier: 'Game',
        season: '1',
        episode: '',
        img: 'https://pbs.twimg.com/media/DROyhtFUQAE1y0k.jpg',
        official: 'http://lostorage-wixoss.com/',
        description: '「歡迎你，selector」被選為selector的人類，必須賭上裝滿自己全部記憶的5枚硬幣來參加戰鬥。取回所有的硬幣並贏得勝利的話，即可從遊戲當中逃脫。相反，失去全部的硬幣，並慘遭敗北的話，其懲罰是——。',
    },
    {
        name: '信長的忍者',
        nameInJpn: '信長の忍び～姉川・石山篇～',
        date: '4/6',
        time: '25:35',
        carrier: 'Comic',
        season: '3',
        episode: '',
        img: 'https://i.imgur.com/ogsP2eD.jpg',
        official: 'https://nobunaga-no-shinobi.com/',
        description: '此作品以日本戰國時代為背景，少女忍者千鳥和她的主君織田信長以及他們的夥伴以終結亂世、統一天下為目標的故事。',
    },
    {
        name: '魔法少女網站',
        nameInJpn: '魔法少女サイト',
        date: '4/7',
        time: '26:25',
        carrier: '26:25',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/dzU8dHW.jpg',
        official: 'http://mahoushoujyo-anime.com/',
        description: '朝霧彩在學校受到欺負，在家裡受到虐待，於是對人生感到絕望，正想要尋死時，卻遇見魔法少女網站，獲得了魔法的力量，並且第一次使用就無意間殺死兩個人……魔法少女網站究竟是什麼？網站上面的 TEMPEST 倒數計時是什麼？為何會有魔法少女不惜縮短自己的性命也想獲得強大力量？以黑暗面出發，一群深信魔法不是為了帶來幸福，而是為了走出不幸的灰暗魔法少女，將帶給您不一樣的魔法少女世界！',
    },
    {
        name: '我的英雄學院',
        nameInJpn: '僕のヒーローアカデミア',
        date: '4/7',
        time: '17:30',
        carrier: 'Comic',
        season: '3',
        episode: '',
        img: 'https://i.imgur.com/RRi60Jy.png',
        official: 'http://heroaca.com/',
        description: '在這個世界，有五分之四的人都有名為「個性」的超能力，有著以此為非作歹的敵人、以及捉拿他們的英雄。主角綠谷出久是個沒有個性的少年，但他仍憧憬並渴望成為一位英雄，並因此進入培育英雄的雄英高校就讀。',
    },
    {
        name: '棒球大聯盟 2nd',
        nameInJpn: 'MAJOR 2nd',
        date: '4/7',
        time: '17:35',
        carrier: 'Comic',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/QsJHHId.jpg',
        official: 'http://www6.nhk.or.jp/anime/program/detail.html?i=major',
        description: '吾郎的兒子・大吾，因為被沒有才能的事實與二代稱呼重壓，退出了海豚隊。然而就在小六時，放棄棒球的大吾面前出現了一個轉學生。自稱是佐藤壽也的兒子・小光的登場，讓大吾的棒球人生開始有巨大轉變…？',
    },
    {
        name: '藍海少女',
        nameInJpn: 'あまんちゅ！～あどばんす～',
        date: '4/7',
        time: '22:00',
        carrier: 'Comic',
        season: '2',
        episode: '',
        img: 'https://i.imgur.com/EZ4u4Vw.png',
        official: 'http://amanchu-anime.com/',
        description: '喜歡海和潛水的活潑少女・小日向光，從東京搬到鄉下的內向少女・大木雙葉，兩名少女在夢丘高中入學時相遇並加入潛水社。以自然豐饒的伊豆半島為舞台，兩名少女透過潛水享受四季的美好日常生活。',
    },
    {
        name: 'DEVILSLINE 惡魔戰線',
        nameInJpn: 'デビルズライン',
        date: '4/7',
        time: '23:30',
        carrier: 'Comic',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/eANv9wA.jpg',
        official: 'http://devilsline.jp/',
        description: '故事以人類和吸血鬼共存的日本做為舞台，因為近期連續發生好幾起「吸血鬼殺人事件」造成人心惶惶，美和子擔心小司的安危，特地要求秋村送小司回家，但是在路上卻遇上安齋。他直接挑明說秋村其實就是吸血鬼，最後還將對方制伏逮捕。後來由安齋護送小司回家，但是他看到小司流血卻忍不住上前去舔，原來安齋本身也是吸血鬼跟人類的混血，目前得靠施打鎮靜劑來保持理智……',
    },
    {
        name: '刀劍神域外傳 Gun Gale Online',
        nameInJpn: 'ソードアート・オンライン オルタナティブ ガンゲイル・オンライン',
        date: '4/7',
        time: '24:00',
        carrier: 'Novel',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/RvF7TLG.jpg',
        official: 'http://gungale-online.net/',
        description: '「蓮」是在槍與鋼鐵的世界《Gun Gale Online》一個人盡情遊玩的女性玩家，她最喜歡可愛的東西，全身的裝備也統一都是粉紅色，又在遊戲裡務實地鍛鍊與成長，累積了一身的實力。然後，因為遇到某件事讓蓮發現PK─狩獵玩家的樂趣，就是沉醉在PK當中，最後終於被別人稱為「粉紅色的惡魔」。',
    },
    {
        name: '女神異聞錄5',
        nameInJpn: 'PERSONA5 the Animation',
        date: '4/7',
        time: '24:30',
        carrier: 'Game',
        season: '5',
        episode: '',
        img: 'https://i.imgur.com/FPiEo5c.jpg',
        official: 'http://p5a.jp/',
        description: '高二的春天，雨宮蓮轉學到了東京的「秀盡學園」。因某事為契機而覺醒為“假面”使用者的蓮，與新認識的夥伴們組建了「心之怪盜團」。怪盜團員們去盜走陷進了罪惡慾望之中的成年人們的“扭曲的慾望“，讓成年人們洗心革面。',
    },
    {
        name: '鬼燈的冷徹',
        nameInJpn: '鬼灯の冷徹 第弐期 その弐',
        date: '4/8',
        time: '0:00',
        carrier: 'Comic',
        season: '2',
        episode: '',
        img: 'https://i.imgur.com/NN5jML9.jpg',
        official: 'http://www.hozukino-reitetsu.com/',
        description: '描述閻羅王手下的第一輔佐官・鬼燈在地獄中充滿超級S的日常生活以及超現實的黑色幽默。主要舞台是描述住在日本的地獄的當地居民們的生活，除此之外還有神話、日本童話、怪談等多數故事人物登場，另外不限於日本，國外的惡魔和妖怪也會出現。*註：此為分開放送，因此季數與上次相同',
    },
    {
        name: '雷頓 懸疑偵探社 ～卡翠愛兒的解謎事件簿～',
        nameInJpn: 'レイトン ミステリー探偵社～カトリーのナゾトキファイル～',
        date: '4/8',
        time: '8:30',
        carrier: 'Game',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/EvRPRe1.png',
        official: 'https://www.layton-anime.jp/',
        description: '卡翠愛兒為了尋找突然失蹤的父親雷頓教授，開始在倫敦從事偵探工作，從尋找走失的寵物貓，到找出殺人事件的犯人等，不論大小案件她都會承接，並以異想天開的解謎手法來解決這些事件。在會說話的狗助手「夏洛」的協助下，展開嶄新的解謎冒險。',
    },
    {
        name: '星光頻道',
        nameInJpn: 'キラッとプリ☆チャン',
        date: '4/8',
        time: '10:00',
        carrier: 'Game',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/KlCjozz.jpg',
        official: 'http://www.takaratomy-arts.co.jp/specials/prichan/',
        description: '憧憬著《星光頻道》的普通中學生．未來與好友．繪萌搭檔，加入經紀人．倫香一起出道成為偶像，以當紅偶像．安那為目標，開始一段艱辛的偶像奮鬥之路。',
    },
    {
        name: '甜心戰士 Universe',
        nameInJpn: 'Cutie Honey Universe',
        date: '4/8',
        time: '21:00',
        carrier: 'Comic',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/fNh0DhW.jpg',
        official: 'http://cutiehoney-u.com/',
        description: '故事描述美少女機器人「如月甜心」如何運用體內的「空中元素固定裝置」，與反派犯罪組織「豹爪」戰鬥的故事。',
    },
    {
        name: 'Caligula',
        nameInJpn: 'Caligula ‐カリギュラ‐',
        date: '4/8',
        time: '23:30',
        carrier: 'Game',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/QdgPf4l.jpg',
        official: 'http://caligula-anime.com/',
        description: '在莫比烏斯世界內，人們不必承受現實世界中的痛苦，並且可以享受虛擬世界的高中生活。 身處在此世界中的主角意識到他們事實上是生活在虛擬世界中。因此他創設了「歸宅部」，目的為逃離莫比烏斯以及監視這個世界的程序「μ」。',
    },
    {
        name: '琴之森',
        nameInJpn: 'ピアノの森',
        date: '4/8',
        time: '24:10',
        carrier: 'Comic',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/jtRm6uE.jpg',
        official: 'http://piano-anime.jp/',
        description: '在「琴之森林」中，有著一台無聲的鋼琴，這個世界上只有一個人能演奏它，那就是在這個森林長大的天才鋼琴少年－一之瀨海，因為這台無聲的舊鋼琴，令阿海遇見了因車禍結束演奏生涯的前天才鋼琴師阿字野壯介和他一生的朋友和對手雨宮修平。',
    },
    {
        name: '食戟之靈 餐之皿 遠月列車篇',
        nameInJpn: '食戟のソーマ 餐の皿 遠月列車篇',
        date: '4/8',
        time: '24:30',
        carrier: 'Comic',
        season: '4',
        episode: '',
        img: 'https://pbs.twimg.com/media/DRKZFppXUAAXdq3.jpg',
        official: 'http://shokugekinosoma.com/',
        description: '位於東京的料理名校「遠月學園」，學生們會以料理來作一對一的比試對決，這種對決叫作「食戟」。家裡經營「幸平餐館」的中學生幸平創真，國中畢業之後，以料理人的父親為目標，每天持續磨練自己的廚藝。',
    },
    {
        name: '美男高校地球防衛部HAPPY KISS！',
        nameInJpn: '美男高校地球防衛部HAPPY KISS！(ハッピーキッス)',
        date: '4/8',
        time: '25:35',
        carrier: 'Original',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/vePFPDQ.jpg',
        official: 'http://boueibu.com/hk/',
        description: '從宇宙飛來的神秘生物創設了立場對立的「防衛部」與「征服部」，就此展開男孩子們為了保護地球變身成愛的王位繼承者「Battle Lovers」與怪物們戰鬥的故事。',
    },
    {
        name: '實驗品家庭',
        nameInJpn: '実験品家族 -クリーチャーズ・ファミリー・デイズ-',
        date: '4/9',
        time: '19:30',
        carrier: 'Comic Novel Game Original',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/GBarFD7.png',
        official: 'http://jp.frankenstein-family.com/',
        description: '丹尼斯的父母是世間無法容許的瘋狂科學家，他們將孩子培育在孤島的研究所，在那邊進行秘密實驗，將除了丹尼斯之外的孩子全都改造成特異人種。一日，秘密島嶼的實驗室被發現了，父母被警察拘捕、孩子們則在社工安排下到另一個小島上居住。問題是，除了丹尼斯以外的四個兄姐，並不具有現代人的常識……究竟他們能否在順利融入社會同時也隱藏好自己的特異身分呢',
    },
    {
        name: '黃金神威',
        nameInJpn: 'ゴールデンカムイ',
        date: '4/9',
        time: '22:00',
        carrier: 'Comic',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/lA5kPjE.png',
        official: 'http://kamuy-anime.com/',
        description: '故事以明治末期的北海道為舞台，描述前士兵「不死身」杉元佐一和愛奴人少女阿席莉帕的尋找黃金的戰鬥冒險故事，並融合了明治末期的北海道之史地文化及建築、愛奴語言風俗、野外生存、狩獵、美食、軍武戰爭等要素。',
    },
    {
        name: '蒼天之拳REGENESIS',
        nameInJpn: '蒼天の拳REGENESIS',
        date: '4/9',
        time: '24:30',
        carrier: 'Comic',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/4MbZa3F.jpg',
        official: 'http://www.souten-regenesis.com/',
        description: '《蒼天之拳》故事作為《北斗之拳》的前傳，描述被稱為北斗神拳 1800 年歷史中最強、第 62 代傳人的霞拳志郎的故事。',
    },
    {
        name: '敦君與女朋友',
        nameInJpn: 'あっくんとカノジョ',
        date: '4/9',
        time: '25:10',
        carrier: 'Comic',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/K9VLhT8.png',
        official: 'http://akkun-kanojo.jp/',
        description: '故事描述莊敦大是一位十七歲高中生，他有一位交往四年的女朋友片桐音， 平時總是對小音口出惡言，滿嘴「煩人」、「噁心」， 這樣的阿敦，他的真實面貌其實是個超愛女朋友的傲嬌跟蹤狂， 竊聽、偷拍、尾隨、錄音無所不來，對男友的行徑截然不知的小音， 即使面對男友的惡言，卻依然能感到阿敦對她的愛！',
    },
    {
        name: '踏切時間',
        nameInJpn: '踏切時間',
        date: '4/9',
        time: '25:15',
        carrier: 'Comic',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/3qg4HNZ.jpg',
        official: 'http://fumikirijikan.com/',
        description: '春宵苦短！哪怕是道口等待的時間也不能浪費！在等列車通過的那點時間閒聊的青春喜劇。',
    },
    {
        name: 'Lady Sports',
        nameInJpn: 'レディスポ',
        date: '4/9',
        time: '25:20',
        carrier: 'Original',
        season: '1',
        episode: '',
        img: 'https://pbs.twimg.com/media/DYOpSI6XcAUhkjK.jpg',
        official: 'https://twitter.com/LaDySp2018',
        description: '本作以席捲全銀河系的宇宙戰爭無果而終的世界為舞台，講述通過體育運動賺取賞金的少女們，縱橫整個宇宙的故事。',
    },
    {
        name: '惡魔高校D×D HERO',
        nameInJpn: 'ハイスクールD×D HERO',
        date: '4/10',
        time: '23:00',
        carrier: 'Novel',
        season: '4',
        episode: '',
        img: 'https://i.imgur.com/Lr3KshPh.jpg',
        official: 'http://www.haremking.tv/',
        description: '故事裡的主角「兵藤一誠」就讀在有著眾多女性的私立駒王學園，在首次的約會卻被自己的女友給殺害，醒來後發現身旁睡著一位全裸的紅髮美少女「莉亞絲」，她向一誠說明讓他重新轉生成為惡魔的事實，並將作為惡魔下僕永遠的跟隨她，自此充滿妄想的愛與青春學園生活就這樣拉開序幕。',
    },
    {
        name: '和風喫茶鹿楓堂',
        nameInJpn: '鹿楓堂よついろ日和',
        date: '4/10',
        time: '24:30',
        carrier: 'Comic',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/UZj9714.jpg',
        official: 'http://rokuhoudou-anime.jp/',
        description: '《鹿楓堂》描述的是聚集了各種心懷煩惱的客人在和風喫茶店鹿楓堂發生的故事。在鹿楓堂有4位能力很強的專業店員，他們一邊為客人提供著美味食物，一邊幫客人們排解各種煩惱.....',
    },
    {
        name: '最終休止符 - 無止境的螺旋物語 -',
        nameInJpn: 'ラストピリオド - 終わりなき螺旋の物語 -',
        date: '4/11',
        time: '24:00',
        carrier: 'Game',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/88WNB3a.jpg',
        official: 'http://lastperiod.jp/',
        description: '「Period」，是將誕生自絕望的異形怪物「Spiral」打倒之人的名號。隸屬於Arc End第8支部的見習Period·哈爾，也為了斬斷絕望的輪迴，而投身於無止境的戰鬥當中……',
    },
    {
        name: 'Butlers～千年百年物語～',
        nameInJpn: 'Butlers～千年百年物語～',
        date: '4/11',
        time: '25:05',
        carrier: 'Original',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/cnMrVIm.jpg',
        official: 'http://www.butlers-anime.com/',
        description: '故事講述頭腦清晰、眉清目秀，以微笑迷惑少女的學生會會長神宮司高馬；多才多藝、溫柔敦厚，擅長咖啡拉花的咖啡店店員羽早川翔，這兩人互為穿越時間命運的宿敵。交織著異能戰鬥及學園喜劇，千年的血緣及百年的思念正交錯著...',
    },
    {
        name: '命運石之門0',
        nameInJpn: 'シュタインズ・ゲート ゼロ',
        date: '4/11',
        time: '25:35',
        carrier: 'Game',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/8Qm5F53.jpg',
        official: 'http://steinsgate0-anime.com/',
        description: 'β世界線。這是「岡部倫太郎」沒能在7月28日救回「牧瀬紅莉栖」之後的故事……對於自己無法拯救紅莉栖而感到失意的岡部，以前往「哥倫比亞大學」就讀為人生目標，展開日復一日的普通大學生活。某天，岡部在協助大學教授進行實驗時，認識了以往和紅莉栖同一組別的教授「亞歷克斯」及前輩「比屋定真帆」。',
    },
    {
        name: 'Hisone 與 Masotan',
        nameInJpn: 'ひそねとまそたん',
        date: '4/12',
        time: '24:00',
        carrier: 'Comic',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/pKgdYMv.jpg',
        official: 'http://hisomaso.com/',
        description: '「我與你一同飛向天空。」甘粕檜曾根，是最近開始在航空自衛隊岐阜基地任職的新人。過於率直而總是無意識地傷害他人，對此感到疲憊不堪的她，選擇成為任期限定的自衛官',
    },
    {
        name: '阿宅的戀愛太難',
        nameInJpn: 'ヲタクに恋は難しい',
        date: '4/12',
        time: '24:55',
        carrier: 'Comic',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/Q65k7iS.png',
        official: 'http://wotakoi-anime.com/',
        description: '動畫御宅族桃瀨成海轉職到新公司後，遇見了是兒時玩伴也是電動宅的二藤宏嵩。兩人成了一起打電動的宅友，並在相同的興趣支持之下開始交往。而公司前輩小柳花子與樺倉太郎表面看似普通，但私下也有不為人知的另一面。',
    },
    {
        name: '奴隸區 The Animation',
        nameInJpn: '奴隷区 The Animation',
        date: '4/12',
        time: '25:05',
        carrier: 'Novel',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/fKT0unv.jpg',
        official: 'http://doreiku-anime.com/',
        description: '這個世界上存在著能夠讓別人服從自己的器具──由 24 位主角所展開的慾望殊死戰！金錢、復仇、愛情……最後的贏家到底是誰？究極奴隸對決!!',
    },
    {
        name: '異世界居酒屋',
        nameInJpn: '異世界居酒屋～古都アイテーリアの居酒屋のぶ～',
        date: '4/13',
        time: '12:00',
        carrier: 'Comic',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/kQt437i.jpg',
        official: 'https://r.gnavi.co.jp/nobu/',
        description: '連接到古都阿伊特力亞的小巷弄里的居酒屋「阿信」。 懶惰的衛兵、子爵家任性的千金小姐、嚴格的包稅人等， 各具特色的異世界居民們，津津有味地享用著陌生的和風居酒屋料理， 接連成為美食的俘虜……！ ？ ',
    },
    {
        name: '驚爆危機 Invisible Victory',
        nameInJpn: 'フルメタル・パニック！Invisible Victory',
        date: '4/13',
        time: '20:30',
        carrier: 'Novel',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/7Fldhhn.jpg',
        official: 'http://fullmeta-iv.com/',
        description: '在「Fantasia 文庫大感謝祭2015」活動上發表將推出新作動畫。 所屬神秘國際軍事組織「秘銀」士兵的相良宗介，他接到了新的任務，化裝為高中生潛入日本東京的一所高中，負責保護一位16 歲的女高中生千鳥要。',
    },
    {
        name: '卡片鬥爭!! 先導者',
        nameInJpn: 'カードファイト!! ヴァンガード',
        date: '5/5',
        time: '21:00',
        carrier: 'Game',
        season: '5',
        episode: '',
        img: 'https://i.imgur.com/dtCYdWF.jpg',
        official: 'https://anime.cf-vanguard.com/',
        description: '高橋和希的徒弟、《遊戲王R》作者伊藤彰新作！比現在稍後不久的未來，世界上玩卡片遊戲的人口已經超過數億人，其中掀起世界性熱潮的卡片遊戲就是“先導者”！主角先導愛知為了奪回自己的王牌狂風劍士與宿敵櫂俊樹展開了對決！',
    },
];
// 讓動畫按時間排序
var Anime = Anime.sort(function(a, b) {
    //new Date(year, month[, day[, hour[, minutes[, seconds[, milliseconds]]]]]);
    var aTime = new Date(2018, a.date.split("/")[0], a.date.split("/")[1], a.time.split(":")[0], a.time.split(":")[1]),
        bTime = new Date(2018, b.date.split("/")[0], b.date.split("/")[1], b.time.split(":")[0], b.time.split(":")[1]);
    return aTime - bTime;
});