//==============================//
//          2018 春番清單
//  github.com/gnehs/Anime-List
//==============================//
//            資料來源
// 維基百科
// https://zh.wikipedia.org/
// 百度百科
// https://baike.baidu.com
// 萌娘百科
// https://zh.moegirl.org/
// Animen 動漫平台
// https://www.animen.com.tw/
// 巴哈
// https://forum.gamer.com.tw/
//==============================//
Anime = [
    // 星期格式 / Week
    //     Sun  Mon Tue  Wed  Thu  Fri  Sat none
    //     日   一   二   三    四   五   六  尚未公開
    // 原作載體 / Carrier
    //     Comic  Novel   Game  Original
    //    漫畫    小說    遊戲   原創或其他
    // 資料存取範例 / Example
    //    -> Anime[0].name
    //    <- LoveLive! SunShine!!
    // 格式範例 / Example
    // {
    //    name: '動畫名稱'
    ,
    //    date: '首次播送日期(ex.6/13)'
    ,
    //    week: '星期(請參照星期格式)'
    ,
    //    time: '首次播送時間'
    ,
    //    carrier: '原作載體(請參照原作載體格式)'
    ,
    //    season: '第?季'
    ,
    //    nameInJpn: '動畫原文名稱'
    ,
    //    img: '海報(請上傳 Ingur 並將網址改成 Https 格式)'
    ,
    //    official: '動畫官網'
    ,
    //    description: '說明文(避免大量劇透)'
    ,
    // }
    ,
    {
        name: '鬼太郎',
        nameInJpn: 'ゲゲゲの鬼太郎',
        date: '4/1',
        time: '9:00',
        carrier: 'Comic',
        season: '6',
        episode: '',
        img: 'https://i.imgur.com/FlSmbcw.jpg',
        official: 'http://www.toei-anim.co.jp/kitaro/',
        description: '故事主軸是闡述作為幽靈族最後倖存者的少年「鬼太郎」，施展妖術和做盡壞事的妖怪們作戰。身穿黃黑橫紋背心和傳統日式木屐的小男孩，以頭髮、坎肩和下馱當武器，與一群住在神秘森林裡的妖怪朋友們一起解決妖怪跟人類兩個世界的麻煩。',
    },
    {
        name: 'B：彼之初',
        nameInJpn: 'B: The Beginning',
        date: '3/2',
        time: '0:00',
        carrier: 'Original',
        season: '1',
        episode: '12',
        img: 'https://i.imgur.com/iGT3yO2.jpg',
        official: 'http://www.b-animation.jp/',
        description: '某天，被稱為天才調查員的奇斯·弗列克來到王立警察特殊犯罪搜査科，並追尋著某件事件的犯人——連環殺手「殺手B」。而在犯案現場內，連環殺手「殺手B」必會刻上字母「B」，總是引起人們的注意，但沒有人知道其意思。「B」只是殺手留給她的信息，想告訴她「我在這裡」。奇斯及黑羽，這兩位陌生人的命運，不久將被一個陰謀吞噬。',
    },
    {
        name: '裝刀凱',
        nameInJpn: 'ソードガイ The Animation',
        date: '3/23',
        time: '0:00',
        carrier: 'Comic',
        season: '1',
        episode: '12',
        img: 'https://i.imgur.com/jHxwmvQ.png',
        official: 'http://swordgai-anime.com/',
        description: '嘗遍無數人鮮血的武器化為傳奇，有時甚至全然不受人控制。當與武器合而為一的人類宿主心中充滿憎恨與殺意時，就會如同惡魔一般渴望大開殺戒。某組織面對這類危險武器的存在長達好幾世紀，而一位名叫「凱」的男子則注定與武器合而為一…',
    },

    {
        name: '甜蜜懲罰～我是看守專用寵物',
        nameInJpn: '甘い懲罰～私は看守専用ペット',
        date: '4/1',
        time: '01:00',
        carrier: 'Comic',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/Wd15gut.jpg',
        official: 'https://kanshu.cf-anime.com',
        description: '早乙女陽菜因為冤罪進入了監獄當中，而負責她的是一位大帥哥看守明神亞貴，而陽菜成為了這個看守的專屬玩具，在牢裡除了這個抖 S 看守外還有為了保護女主角而奔走的黑社會比嘉大和，陽菜本身在監獄外面還有一位男朋友八雲聖德',
    },
    {
        name: '冷然之天秤',
        nameInJpn: 'ニル・アドミラリの天秤',
        date: '4/1',
        time: '22:00',
        carrier: 'Game',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/CWVUs95.jpg',
        official: 'http://nilad-anime.com/',
        description: '故事背景在大正25年間。大地震之後，帝都東京以「和洋混合」的獨特文化形式繼續發展，隨著科技現代化、印刷出版日漸興盛，接連發生了一系列無法解開的謎事件。',
    },
    {
        name: '賽馬娘Pretty Derby',
        nameInJpn: 'ウマ娘 プリティーダービー',
        date: '4/1',
        time: '24:00',
        carrier: 'Game',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/2DAb1dy.png',
        official: 'http://anime-umamusume.jp/',
        description: '這是從異世界傳承下光輝的名字與競跑能力的“馬娘”，自古以來與人類共存著的世界的故事。從鄉下轉學到大都市的訓中學園的馬娘·特別週，與同學們互相切磋、賭上“日本第一馬娘”的稱號，目標：在“Twinkle系列賽”中的勝利！',
    },
    {
        name: '足球小將翼',
        nameInJpn: 'キャプテン翼',
        date: '4/2',
        time: '01:35',
        carrier: 'Comic',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/5PaQixS.png',
        official: 'http://ball-ha-tomodachi.com/',
        description: '內容講述足球技術高超的少年大空翼從小學六年級開始到進入職業足壇之間所發生的故事。',
    },
    {
        name: '龍族拼圖',
        nameInJpn: 'パズドラ',
        date: '4/2',
        time: '18:25',
        carrier: 'Game',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/vozo1qg.jpg',
        official: 'http://www.tv-tokyo.co.jp/anime/pad/',
        description: '無',
    },
    {
        name: '你還不懂群馬',
        nameInJpn: 'お前はまだグンマを知らない',
        date: '4/2',
        time: '20:55',
        carrier: 'Comic',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/Jz57X2B.jpg',
        official: 'https://omagun.com/',
        description: '本作敘述男高中生神月紀從千葉縣轉學來群馬縣，沒想到在新幹線上發生了令人匪夷所思的事情。朋友奉勸他不要來，這裡沒人能活著出去。這輛列車在到達群馬縣之前，不會在任何車站開門。車上乘客都是一看就是不正常的人，他還要在被捆綁的情況下回答奇葩的問題......。',
    },
    {
        name: '魔法少女 我',
        nameInJpn: '魔法少女 俺',
        date: '4/2',
        time: '22:00',
        carrier: 'Comic',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/QbD5eZn.jpg',
        official: 'http://magicalgirl-ore.com/',
        description: '主角卯野咲是新生偶像團體「Magical Twin」的成員，為了守護自己所憧憬的偶像團體「STAR☆RICE」成員御翔桃拾而願意奉獻一切。就在某一天，她得知母親曾經是魔法少女而感到震驚。然後，咲為了守護桃拾的願望而變成了男性形態的「魔法少女」。',
    },
    {
        name: '妖怪旅館營業中',
        nameInJpn: 'かくりよの宿飯',
        date: '4/2',
        time: '22:30',
        carrier: 'Novel',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/uvMoQkr.jpg',
        official: 'http://kakuriyo-anime.com/',
        description: '老字號旅館「天神屋」，座落於妖魔鬼怪所棲息的世界──隱世。看得見妖怪的善良女大學生葵，不知不覺中養成做料理餵食妖怪的習慣。某天，葵在餵食妖怪時，突然被天神屋的「大老闆」鬼神給抓走了。根據大老闆所言，葵成了祖父欠下巨債的「擔保品」，必須嫁入他們家。',
    },
    {
        name: '宇宙戰艦提拉米蘇',
        nameInJpn: '宇宙戦艦ティラミス',
        date: '4/3',
        time: '0:00',
        carrier: 'Comic',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/LD7atZF.jpg',
        official: 'http://tiramisu-anime.com/',
        description: '主角是前途似錦的王牌駕駛員一之瀨昴，但不善交際的他在船上一直交不到朋友，也因此總是莫名其妙地做出一些搞笑的脫序行為…… ',
    },
    {
        name: '鋼彈創鬥者潛網大戰',
        nameInJpn: 'ガンダムビルドダイバーズ',
        date: '4/2',
        time: '25:00',
        carrier: 'Comic',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/Jv269fe.jpg',
        official: 'http://tiramisu-anime.com/',
        description: '主角是前途似錦的王牌駕駛員一之瀨昴，但不善交際的他在船上一直交不到朋友，也因此總是莫名其妙地做出一些搞笑的脫序行為…… ',
    },
    {
        name: '東京喰種：re',
        nameInJpn: '東京喰種：re',
        date: '4/3',
        time: '23:00',
        carrier: 'Comic',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/Y76If7F.jpg',
        official: 'http://www.marv.jp/special/tokyoghoul/',
        description: '混在人群當中，吞食人類的血肉。儘管擁有人類的外觀，卻是與人類相異的存在…”喰種”。負責驅逐、研究”喰種”的〔CCG〕，為了完成某個命題，新設立一個實驗體集團。──其名稱是「Qs昆克斯」。非「一般人類」的他們，與佐佐木琲世一等搜查官，他們在”東京”這座城市要面對的東西會是什麼──？',
    },
    {
        name: '立花館戀愛三角關係',
        nameInJpn: '立花館To Lieあんぐる',
        date: '4/3',
        time: '25:00',
        carrier: 'Comic',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/LovtWHF.jpg',
        official: 'http://tachibanakan-anime.com/',
        description: '夏乃花火回到她在六年前離開的鄉下城鎮就讀高中，原本應該入住時尚宿舍「橘館」的她卻因為阿姨的疏失，來到破舊公寓「立花館」開始新生活。夏乃花火在那裡遇見她的兒時玩伴與幾位奇怪的房客，並決定要在完成住滿一個月的租約後搬離立花館。',
    },
    {
        name: '魯邦三世 PART5',
        nameInJpn: 'ルパン三世 PART5',
        date: '4/3',
        time: '25:29',
        carrier: 'Comic',
        season: '5',
        episode: '',
        img: 'https://i.imgur.com/syTVZCK.jpg',
        official: 'https://lupin-pt5.com/',
        description: '魯邦三世是怪盜紳士亞森·魯邦的孫子，被稱為世界最傑出的神偷，在偷東西前總是會發出預告信。他與拔槍只需0.3秒的神槍手次元大介，神秘歐亞混血女盜峰不二子，無所不斬的居合道高手石川五右衛門合作偷遍全世界。錢形平次的後裔，警部錢形幸一一直想要逮捕他們，但全部以失敗告終。',
    },
    {
        name: '3D彼女',
        nameInJpn: '3D彼女 リアルガール',
        date: '4/3',
        time: '25:59',
        carrier: 'Comic',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/Zz73HM8.jpg',
        official: 'http://www.3dkanojo-anime.com/',
        description: '筒井光，是一個滿足於動漫以及遊戲中虛擬女孩的高中生。某一天，陷入和現充女色葉一起被罰清掃游泳池的窘境。打扮花哨又擺架子而且出了名和男生關係亂的百分百現充女‧色葉 謎樣地急速接近！不不不…你和我、完全就不是一路人啊！',
    },
    {
        name: 'ALICE OR ALICE 妹控哥哥與雙胞胎妹妹',
        nameInJpn: 'ありすorありす ～シスコン兄さんと双子の妹～',
        date: '4/4',
        time: '22:55',
        carrier: 'Comic',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/AF5bO4Q.jpg',
        official: 'http://alice-or-alice.com/',
        description: '這是一個由愛莉、莉絲兩個雙胞胎以及一個妹控哥哥組成的故事，寵溺妹妹的哥哥關於妹妹的事情無所不知！一面獨占著又寵溺著愛吃甜食、愛撒嬌妹妹們的萌萌日常生活。',
    },
    {
        name: '重神機潘多拉',
        nameInJpn: '重神機パンドーラ',
        date: '4/4',
        time: '23:30',
        carrier: 'Original',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/HY9APJH.jpg',
        official: 'http://www.project-the-next.com/',
        description: '描述環境因某起事故而發生劇變，由此誕生的超級生物給人們帶來了災難，被放逐的天才科學家主人公為了對抗這類生物而開展獨自研究。作品的舞台則是以中國重慶為原型。',
    },
    {
        name: '罪人與龍共舞',
        nameInJpn: 'されど罪人は竜と踊る',
        date: '4/5',
        time: '01:58',
        carrier: 'Novel',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/sx6I47Z.png',
        official: 'http://www.tbs.co.jp/anime/sareryu/',
        description: '所謂的咒式，乃操作作用子定數h，讓物理法則發生局部變化，產生TNT炸藥與毒氣，並引發電漿與核融合之類強烈物理現象的方程式。兩名使用咒式的進攻型咒式士，想擺脫惡運纏身的嘉優斯，以及殘酷的俊美劍士吉吉那。追尋「異貌者」和賞金通緝要犯的兩人，被捲入艾理達那上「龍」的戰爭以及大國的陰謀中……。',
    },
    {
        name: 'Aikatsu! 偶像學園！Friends',
        nameInJpn: 'アイカツフレンズ！',
        date: '4/5',
        time: '18:25',
        carrier: 'Game',
        season: '3',
        episode: '',
        img: 'https://i.imgur.com/J1KfnPj.jpg',
        official: 'http://www.aikatsu.com/friends/teaser/',
        description: '無',
    },
    {
        name: '多田君不談戀愛',
        nameInJpn: '多田くんは恋をしない',
        date: '4/5',
        time: '21:00',
        carrier: 'Original',
        season: '1',
        episode: '',
        img: 'https://i.imgur.com/LcdnnBF.jpg',
        official: 'http://tadakoi.tv/',
        description: '手持相機，拍攝盛開櫻花照片的多田光良，與剛剛從異國他鄉來到日本的少女特蕾莎·華格納相遇了。從歐洲的拉森堡來到日本留學的特蕾莎，剛一到達日本，就和一起過來的夥伴走散而迷路了。由此而開始幫助她的光良，將特蕾莎帶到了祖父經營的多田咖啡店……',
    },
    {
        name: '銀河英雄傳說 Die Neue These',
        nameInJpn: '銀河英雄伝説 Die Neue These 邂逅',
        date: 'aaa',
        time: 'aaa',
        carrier: 'Comic Novel Game Original',
        season: 'aaa',
        episode: '',
        img: 'aaaa',
        official: 'aaa',
        description: 'aaa',
    },
    {
        name: '漫畫女孩（Comic Girls）',
        nameInJpn: 'こみっくがーるず',
        date: 'aaa',
        time: 'aaa',
        carrier: 'Comic Novel Game Original',
        season: 'aaa',
        episode: '',
        img: 'aaaa',
        official: 'aaa',
        description: 'aaa',
    },
    {
        name: 'MEGALO BOX',
        nameInJpn: 'メガロボクス',
        date: 'aaa',
        time: 'aaa',
        carrier: 'Comic Novel Game Original',
        season: 'aaa',
        episode: '',
        img: 'aaaa',
        official: 'aaa',
        description: 'aaa',
    },
    {
        name: '閃電十一人 戰神的天秤',
        nameInJpn: 'イナズマイレブン アレスの天秤',
        date: 'aaa',
        time: 'aaa',
        carrier: 'Comic Novel Game Original',
        season: 'aaa',
        episode: '',
        img: 'aaaa',
        official: 'aaa',
        description: 'aaa',
    },
    {
        name: '極道超女',
        nameInJpn: 'ヒナまつり',
        date: 'aaa',
        time: 'aaa',
        carrier: 'Comic Novel Game Original',
        season: 'aaa',
        episode: '',
        img: 'aaaa',
        official: 'aaa',
        description: 'aaa',
    },
    {
        name: '錢進球場',
        nameInJpn: 'グラゼニ',
        date: 'aaa',
        time: 'aaa',
        carrier: 'Comic Novel Game Original',
        season: 'aaa',
        episode: '',
        img: 'aaaa',
        official: 'aaa',
        description: 'aaa',
    },
    {
        name: 'LOST SONG',
        nameInJpn: 'LOST SONG',
        date: 'aaa',
        time: 'aaa',
        carrier: 'Comic Novel Game Original',
        season: 'aaa',
        episode: '',
        img: 'aaaa',
        official: 'aaa',
        description: 'aaa',
    },
    {
        name: 'Lostorage conflated WIXOSS',
        nameInJpn: 'ロストレージインサイテッドウィクロス',
        date: 'aaa',
        time: 'aaa',
        carrier: 'Comic Novel Game Original',
        season: 'aaa',
        episode: '',
        img: 'aaaa',
        official: 'aaa',
        description: 'aaa',
    },
    {
        name: 'SERVAMP-吸血鬼僕人-Alice in the Garden',
        nameInJpn: 'SERVAMP-サーヴァンプ-Alice in the Garden- ',
        date: 'aaa',
        time: 'aaa',
        carrier: 'Comic Novel Game Original',
        season: 'aaa',
        episode: '',
        img: 'aaaa',
        official: 'aaa',
        description: 'aaa',
    },
    {
        name: '信長的忍者 第3期',
        nameInJpn: '信長の忍び～姉川・石山篇～',
        date: 'aaa',
        time: 'aaa',
        carrier: 'Comic Novel Game Original',
        season: 'aaa',
        episode: '',
        img: 'aaaa',
        official: 'aaa',
        description: 'aaa',
    },
    {
        name: '魔法少女網站',
        nameInJpn: '魔法少女サイト',
        date: 'aaa',
        time: 'aaa',
        carrier: 'Comic Novel Game Original',
        season: 'aaa',
        episode: '',
        img: 'aaaa',
        official: 'aaa',
        description: 'aaa',
    },
    {
        name: '我的英雄學院 第3期',
        nameInJpn: '僕のヒーローアカデミア 第3期',
        date: 'aaa',
        time: 'aaa',
        carrier: 'Comic Novel Game Original',
        season: 'aaa',
        episode: '',
        img: 'aaaa',
        official: 'aaa',
        description: 'aaa',
    },
    {
        name: '棒球大聯盟2nd',
        nameInJpn: 'MAJOR 2nd',
        date: 'aaa',
        time: 'aaa',
        carrier: 'Comic Novel Game Original',
        season: 'aaa',
        episode: '',
        img: 'aaaa',
        official: 'aaa',
        description: 'aaa',
    },
    {
        name: '藍海少女 第2期',
        nameInJpn: 'あまんちゅ！～あどばんす～',
        date: 'aaa',
        time: 'aaa',
        carrier: 'Comic Novel Game Original',
        season: 'aaa',
        episode: '',
        img: 'aaaa',
        official: 'aaa',
        description: 'aaa',
    },
    {
        name: 'DEVILSLINE 惡魔戰線',
        nameInJpn: 'デビルズライン',
        date: 'aaa',
        time: 'aaa',
        carrier: 'Comic Novel Game Original',
        season: 'aaa',
        episode: '',
        img: 'aaaa',
        official: 'aaa',
        description: 'aaa',
    },
    {
        name: '刀劍神域外傳 Gun Gale Online',
        nameInJpn: 'ソードアート・オンライン オルタナティブ ガンゲイル・オンライン',
        date: 'aaa',
        time: 'aaa',
        carrier: 'Comic Novel Game Original',
        season: 'aaa',
        episode: '',
        img: 'aaaa',
        official: 'aaa',
        description: 'aaa',
    },
    {
        name: '女神異聞錄5 the Animation',
        nameInJpn: 'PERSONA5 the Animation',
        date: 'aaa',
        time: 'aaa',
        carrier: 'Comic Novel Game Original',
        season: 'aaa',
        episode: '',
        img: 'aaaa',
        official: 'aaa',
        description: 'aaa',
    },
    {
        name: '鬼燈的冷徹　2期之2',
        nameInJpn: '鬼灯の冷徹 第弐期 その弐',
        date: 'aaa',
        time: 'aaa',
        carrier: 'Comic Novel Game Original',
        season: 'aaa',
        episode: '',
        img: 'aaaa',
        official: 'aaa',
        description: 'aaa',
    },
    {
        name: '雷頓 懸疑偵探社 ～卡翠愛兒的解謎事件簿～',
        nameInJpn: 'レイトン ミステリー探偵社～カトリーのナゾトキファイル～',
        date: 'aaa',
        time: 'aaa',
        carrier: 'Comic Novel Game Original',
        season: 'aaa',
        episode: '',
        img: 'aaaa',
        official: 'aaa',
        description: 'aaa',
    },
    {
        name: '星光頻道',
        nameInJpn: 'キラッとプリ☆チャン',
        date: 'aaa',
        time: 'aaa',
        carrier: 'Comic Novel Game Original',
        season: 'aaa',
        episode: '',
        img: 'aaaa',
        official: 'aaa',
        description: 'aaa',
    },
    {
        name: '甜心戰士Universe',
        nameInJpn: 'Cutie Honey Universe',
        date: 'aaa',
        time: 'aaa',
        carrier: 'Comic Novel Game Original',
        season: 'aaa',
        episode: '',
        img: 'aaaa',
        official: 'aaa',
        description: 'aaa',
    },
    {
        name: 'Caligula',
        nameInJpn: 'Caligula ‐カリギュラ‐',
        date: 'aaa',
        time: 'aaa',
        carrier: 'Comic Novel Game Original',
        season: 'aaa',
        episode: '',
        img: 'aaaa',
        official: 'aaa',
        description: 'aaa',
    },
    {
        name: '琴之森',
        nameInJpn: 'ピアノの森',
        date: 'aaa',
        time: 'aaa',
        carrier: 'Comic Novel Game Original',
        season: 'aaa',
        episode: '',
        img: 'aaaa',
        official: 'aaa',
        description: 'aaa',
    },
    {
        name: '食戟之靈 餐之皿 遠月列車篇',
        nameInJpn: '食戟のソーマ 餐の皿 遠月列車篇',
        date: 'aaa',
        time: 'aaa',
        carrier: 'Comic Novel Game Original',
        season: 'aaa',
        episode: '',
        img: 'aaaa',
        official: 'aaa',
        description: 'aaa',
    },
    {
        name: '美男高校地球防衛部HAPPY KISS！',
        nameInJpn: '美男高校地球防衛部HAPPY KISS！(ハッピーキッス)',
        date: 'aaa',
        time: 'aaa',
        carrier: 'Comic Novel Game Original',
        season: 'aaa',
        episode: '',
        img: 'aaaa',
        official: 'aaa',
        description: 'aaa',
    },
    {
        name: '實驗品家庭',
        nameInJpn: '実験品家族 -クリーチャーズ・ファミリー・デイズ-',
        date: 'aaa',
        time: 'aaa',
        carrier: 'Comic Novel Game Original',
        season: 'aaa',
        episode: '',
        img: 'aaaa',
        official: 'aaa',
        description: 'aaa',
    },
    {
        name: '黃金神威',
        nameInJpn: 'ゴールデンカムイ',
        date: 'aaa',
        time: 'aaa',
        carrier: 'Comic Novel Game Original',
        season: 'aaa',
        episode: '',
        img: 'aaaa',
        official: 'aaa',
        description: 'aaa',
    },
    {
        name: '蒼天之拳REGENESIS',
        nameInJpn: '蒼天の拳REGENESIS',
        date: 'aaa',
        time: 'aaa',
        carrier: 'Comic Novel Game Original',
        season: 'aaa',
        episode: '',
        img: 'aaaa',
        official: 'aaa',
        description: 'aaa',
    },
    {
        name: '敦君與女朋友',
        nameInJpn: 'あっくんとカノジョ',
        date: 'aaa',
        time: 'aaa',
        carrier: 'Comic Novel Game Original',
        season: 'aaa',
        episode: '',
        img: 'aaaa',
        official: 'aaa',
        description: 'aaa',
    },
    {
        name: '踏切時間',
        nameInJpn: '踏切時間',
        date: 'aaa',
        time: 'aaa',
        carrier: 'Comic Novel Game Original',
        season: 'aaa',
        episode: '',
        img: 'aaaa',
        official: 'aaa',
        description: 'aaa',
    },
    {
        name: 'Ladyspo',
        nameInJpn: 'レディスポ',
        date: 'aaa',
        time: 'aaa',
        carrier: 'Comic Novel Game Original',
        season: 'aaa',
        episode: '',
        img: 'aaaa',
        official: 'aaa',
        description: 'aaa',
    },
    {
        name: '惡魔高校D×D HERO',
        nameInJpn: 'ハイスクールD×D HERO',
        date: 'aaa',
        time: 'aaa',
        carrier: 'Comic Novel Game Original',
        season: 'aaa',
        episode: '',
        img: 'aaaa',
        official: 'aaa',
        description: 'aaa',
    },
    {
        name: '和風喫茶鹿楓堂',
        nameInJpn: '鹿楓堂よついろ日和',
        date: 'aaa',
        time: 'aaa',
        carrier: 'Comic Novel Game Original',
        season: 'aaa',
        episode: '',
        img: 'aaaa',
        official: 'aaa',
        description: 'aaa',
    },
    {
        name: '最終休止符 - 無止境的螺旋物語 -',
        nameInJpn: 'ラストピリオド - 終わりなき螺旋の物語 -',
        date: 'aaa',
        time: 'aaa',
        carrier: 'Comic Novel Game Original',
        season: 'aaa',
        episode: '',
        img: 'aaaa',
        official: 'aaa',
        description: 'aaa',
    },
    {
        name: 'Butlers～千年百年物語～',
        nameInJpn: 'Butlers～千年百年物語～',
        date: 'aaa',
        time: 'aaa',
        carrier: 'Comic Novel Game Original',
        season: 'aaa',
        episode: '',
        img: 'aaaa',
        official: 'aaa',
        description: 'aaa',
    },
    {
        name: '命運石之門0',
        nameInJpn: 'シュタインズ・ゲート ゼロ',
        date: 'aaa',
        time: 'aaa',
        carrier: 'Comic Novel Game Original',
        season: 'aaa',
        episode: '',
        img: 'aaaa',
        official: 'aaa',
        description: 'aaa',
    },
    {
        name: 'Hisone 與 Masotan',
        nameInJpn: 'ひそねとまそたん',
        date: 'aaa',
        time: 'aaa',
        carrier: 'Comic Novel Game Original',
        season: 'aaa',
        episode: '',
        img: 'aaaa',
        official: 'aaa',
        description: 'aaa',
    },
    {
        name: '阿宅的戀愛太難',
        nameInJpn: 'ヲタクに恋は難しい',
        date: 'aaa',
        time: 'aaa',
        carrier: 'Comic Novel Game Original',
        season: 'aaa',
        episode: '',
        img: 'aaaa',
        official: 'aaa',
        description: 'aaa',
    },
    {
        name: '奴隸區 The Animation',
        nameInJpn: '奴隷区 The Animation',
        date: 'aaa',
        time: 'aaa',
        carrier: 'Comic Novel Game Original',
        season: 'aaa',
        episode: '',
        img: 'aaaa',
        official: 'aaa',
        description: 'aaa',
    },
    {
        name: '異世界居酒屋',
        nameInJpn: '異世界居酒屋～古都アイテーリアの居酒屋のぶ～',
        date: 'aaa',
        time: 'aaa',
        carrier: 'Comic Novel Game Original',
        season: 'aaa',
        episode: '',
        img: 'aaaa',
        official: 'aaa',
        description: 'aaa',
    },
    {
        name: '驚爆危機 Invisible Victory',
        nameInJpn: 'フルメタル・パニック！Invisible Victory',
        date: 'aaa',
        time: 'aaa',
        carrier: 'Comic Novel Game Original',
        season: 'aaa',
        episode: '',
        img: 'aaaa',
        official: 'aaa',
        description: 'aaa',
    },
    {
        name: '卡片鬥爭!! 先導者 第五期',
        nameInJpn: 'カードファイト!! ヴァンガード',
        date: 'aaa',
        time: 'aaa',
        carrier: 'Comic Novel Game Original',
        season: 'aaa',
        episode: '',
        img: 'aaaa',
        official: 'aaa',
        description: 'aaa',
    },
];
// 讓動畫按時間排序
var Anime = Anime.sort(function(a, b) {
    return a.date.split("/")[1] - b.date.split("/")[1];
});